export const skillsIcons = {
	dark: {
		html: '/img/skills/dark/html.svg',
		css: '/img/skills/dark/css.svg',
		javascript: '/img/skills/dark/javascript.svg',
		typescript: '/img/skills/dark/typescript.svg',
		react: '/img/skills/dark/react.svg',
		nextjs: '/img/skills/dark/nextjs.svg',
		redux: '/img/skills/dark/redux.svg',
		angular: '/img/skills/dark/angular.svg',
		jquery: '/img/skills/dark/jquery.svg',
		bootstrap: '/img/skills/dark/bootstrap.svg',
		tailwindcss: '/img/skills/dark/tailwind.svg',
		git: '/img/skills/dark/git.svg',
		github: '/img/skills/dark/github.svg',
		gitlab: '/img/skills/dark/gitlab.svg',
		mysql: '/img/skills/dark/mysql.svg',
		mongodb: '/img/skills/dark/mongodb.svg',
		figma: '/img/skills/dark/figma.svg',
	},
	light: {
		html: '/img/skills/light/html.svg',
		css: '/img/skills/light/css.svg',
		javascript: '/img/skills/light/javascript.svg',
		typescript: '/img/skills/light/typescript.svg',
		react: '/img/skills/light/react.svg',
		nextjs: '/img/skills/light/nextjs.svg',
		redux: '/img/skills/light/redux.svg',
		angular: '/img/skills/light/angular.svg',
		jquery: '/img/skills/light/jquery.svg',
		bootstrap: '/img/skills/light/bootstrap.svg',
		tailwindcss: '/img/skills/light/tailwind.svg',
		git: '/img/skills/light/git.svg',
		github: '/img/skills/light/github.svg',
		gitlab: '/img/skills/light/gitlab.svg',
		mysql: '/img/skills/light/mysql.svg',
		mongodb: '/img/skills/light/mongodb.svg',
		figma: '/img/skills/light/figma.svg',
	}
} as const;
